name: flutter_live_location_tracking
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_polyline_points: ^2.1.0
  google_maps_flutter: ^2.10.0
  location: ^7.0.1
  maps_toolkit: ^3.0.0
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  custom_info_window: ^1.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
